#!/bin/bash

# Add webadmin group
sudo groupadd webadmin
sudo usermod -a -G webadmin www-data

# Webserver manager - to gain privileged access to www-data
gcc -o ./bin/webserver_manager ./webserver_manager.c
sudo chown root:root ./bin/webserver_manager
sudo chmod 4511 ./bin/webserver_manager

# Certbot manager - to gain privileged access to www-data
gcc -o ./bin/certbot_manager ./certbot_manager.c
sudo chown root:root ./bin/certbot_manager
sudo chmod 4511 ./bin/certbot_manager

# Install dependencies for webadmin + publish .env
sudo -u www-data -g webadmin composer install
sudo -u www-data -g webadmin cp .env.example .env
sudo -u www-data -g webadmin cp digitalocean.ini.example digitalocean.ini
sudo -u www-data -g webadmin php artisan key:generate

echo "Please update the .env and digitalocean.ini files!\n"
