#!/bin/bash

# Add webadmin group
sudo groupadd webadmin
sudo usermod -a -G webadmin www-data

sudo -u www-data -g webadmin cp .env.example .env
sudo -u www-data -g webadmin php artisan key:generate
sudo -u www-data -g webadmin composer install

# Webserver manager - to gain privileged access to www-data
gcc -o ./bin/webserver_manager ./webserver_manager.c
sudo chmod 4511 ./bin/webserver_manager
sudo chown root:root ./bin/webserver_manager

# Certbot manager - to gain privileged access to www-data
gcc -o ./bin/certbot_manager ./certbot_manager.c
sudo chmod 4511 ./bin/certbot_manager
sudo chown root:root ./bin/certbot_manager



# sudo -u root -g webadmin mkdir /var/letsencrypt
# chmod g=rwx /var/letsencrypt
# sudo -u root -g webadmin mkdir /var/letsencrypt/{config,work,logs}
# chmod g=rwx /var/letsencrypt/{config,work,logs}
